name: SMC Trading Bot 24/7

on:
  schedule:
    # Chạy mỗi 15 phút (4 lần/giờ = 96 lần/ngày)
    - cron: '*/15 * * * *'
  
  # Cho phép chạy thủ công
  workflow_dispatch:
    inputs:
      auto_trade:
        description: 'Enable Auto Trading (true/false)'
        required: false
        default: 'false'

jobs:
  smc-trading:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget build-essential
        
    - name: Install TA-Lib
      run: |
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv pybit pandas numpy TA-Lib matplotlib plotly
        
    - name: Create environment file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" > .env
        echo "API_SECRET=${{ secrets.API_SECRET }}" >> .env
        echo "AUTO_TRADE=${{ github.event.inputs.auto_trade || 'false' }}" >> .env
        echo "POSITION_SIZE_USDT=25" >> .env
        echo "SYMBOL=BTCUSDT" >> .env
        echo "LEVERAGE=5" >> .env
        echo "RISK_PERCENT=1.0" >> .env
        
    - name: Run SMC Bot Analysis
      run: |
        python github_actions_bot.py
        
    - name: Upload trade logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trade-logs-${{ github.run_number }}
        path: |
          trade_log.txt
          *.log
        retention-days: 30